export const orgObj2 = [
  {
    id: "ナイショ",
    imgURL: "/corn.png",
    engName: "ベビーコーン",
    jpName: "たなちゅー",
    height: "ちょうどいい",
    weight: "気にしてる",
    type: "遊び心を大事に",
  },
  {
    id: "ナイショ",
    imgURL: "/ikko.jpeg",
    engName: "もってる",
    jpName: "JINさん",
    height: "高め",
    weight: "ないしょだよ",
    type: "BTC5の笑顔メーカー",
  },
  {
    id: "ナイショ",
    imgURL: "/bono.png",
    engName: "kunokuno",
    jpName: "くのくの",
    height: "高め",
    weight: "ないしょだよ",
    type: "丁寧さと安心感",
  },
  {
    id: "ナイショ",
    imgURL: "/iyashi.jpeg",
    engName: "hasshi-",
    jpName: "はっしー",
    height: "いい感じ",
    weight: "いい感じ",
    type: "落ち着きと包容力",
  },
  {
    id: "ナイショ",
    imgURL: "/pakuchi.jpeg",
    engName: "パクチー",
    jpName: "ぶっちー",
    height: "いい感じ",
    weight: "いい感じ",
    type: "実はインドア派",
  },
  {
    id: "ナイショ",
    imgURL: "/ninjya.jpeg",
    engName: "忍者",
    jpName: "おがちゃん",
    height: "すてき",
    weight: "すてき",
    type: "[性能]GPT < おがPT",
  },
  {
    id: "ナイショ",
    imgURL: "/kiran.png",
    engName: "shun",
    jpName: "しゅん",
    height: "高め",
    weight: "羨ましい",
    type: "検索力の高さと落ち着き",
  },
  {
    id: "ナイショ",
    imgURL: "/akarui.jpeg",
    engName: "naoko",
    jpName: "なお",
    height: "りんご3個ぶん",
    weight: "りんご3個ぶん",
    type: "明るさと地元愛",
  },
  {
    id: "ナイショ",
    imgURL: "/DQ5.png",
    engName: "Taka",
    jpName: "たか",
    height: "いい感じ〜",
    weight: "いい感じ〜",
    type: "まじめさとDQ5",
  },
  {
    id: "151？",
    imgURL: "/myu.jpeg",
    engName: "myu",
    jpName: "ミュウ",
    height: "伝説",
    weight: "伝説",
    type: "スピードスター",
  },
  {
    id: "ナイショ",
    imgURL: "/katana.png",
    engName: "Tatsu",
    jpName: "たつ",
    height: "Good",
    weight: "Good",
    type: "質問の切れ味ばつぐん",
  },
  {
    id: "ナイショ",
    imgURL: "/kansya.png",
    engName: "sho-go",
    jpName: "しょーご",
    height: "よきかなー",
    weight: "よきよき",
    type: "情報シェアにありがとう",
  },
  {
    id: "ナイショ",
    imgURL: "/yukidaruma.jpeg",
    engName: "orazo-",
    jpName: "りょーぞー",
    height: "白塗り",
    weight: "本気",
    type: "大トリで緊張中",
  },
  {
    id: "ナイショ",
    imgURL: "/dori.jpeg",
    engName: "チャリでドリフト",
    jpName: "まぁや",
    height: "りんご3個分",
    weight: "りんご3個分",
    type: "明るさで助けられる",
  },
  {
    id: "ナイショ",
    imgURL: "/controler.png",
    engName: "gon",
    jpName: "ごん",
    height: "お子さん",
    weight: "お大事に",
    type: "生粋のゲーマーです",
  },
  {
    id: "ナイショ",
    imgURL: "/hayao.jpeg",
    engName: "miyazaki",
    jpName: "よこちん",
    height: "双子なので2倍",
    weight: "双子なので2倍",
    type: "BTC5の宮崎駿",
  },
  {
    id: "ナイショ",
    imgURL: "/test.png",
    engName: "kakeru",
    jpName: "Kakeruさん",
    height: "いい感じー",
    weight: "いい感じー",
    type: "アセスメント直後に講義率高め",
  },
  {
    id: "ナイショ",
    imgURL: "/jet.png",
    engName: "Ai",
    jpName: "Aiさん",
    height: "りんご3個分",
    weight: "りんご3個分",
    type: "海の向こうからこんにちは",
  },
  {
    id: "ナイショ",
    imgURL: "/radio.jpeg",
    engName: "Ayumi",
    jpName: "Ayumiさん",
    height: "りんご3個分",
    weight: "りんご3個分",
    type: "お子さんの声に癒された",
  },
];
